// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhK5kCZ5laSRGIvXJgRePAsMfn9xD-vY',
    appId: '1:675665172677:web:686c8fb76b58d620f938ac',
    messagingSenderId: '675665172677',
    projectId: 'phan-anh-do-thi-79f8c',
    authDomain: 'phan-anh-do-thi-79f8c.firebaseapp.com',
    storageBucket: 'phan-anh-do-thi-79f8c.appspot.com',
    measurementId: 'G-LH6LSNBJTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVBdh4hf50c8FqBfzsnVB2ofvw6gmsho',
    appId: '1:675665172677:android:a38640386290a634f938ac',
    messagingSenderId: '675665172677',
    projectId: 'phan-anh-do-thi-79f8c',
    storageBucket: 'phan-anh-do-thi-79f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVOBj1IAtkFBECbyd8bj7gJVwDf559h4',
    appId: '1:675665172677:ios:469c69fe01bf3f70f938ac',
    messagingSenderId: '675665172677',
    projectId: 'phan-anh-do-thi-79f8c',
    storageBucket: 'phan-anh-do-thi-79f8c.appspot.com',
    iosBundleId: 'n.quang.padt.phanAnhDoThi3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtVOBj1IAtkFBECbyd8bj7gJVwDf559h4',
    appId: '1:675665172677:ios:cce7a6329f69f1adf938ac',
    messagingSenderId: '675665172677',
    projectId: 'phan-anh-do-thi-79f8c',
    storageBucket: 'phan-anh-do-thi-79f8c.appspot.com',
    iosBundleId: 'n.quang.padt.phanAnhDoThi3.RunnerTests',
  );
}
